name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login docker regsitry
        run: docker login -u ${{ secrets.DOCKER_USER }} -p  ${{ secrets.DOCKER_USER_PASSWORD }}
      - name: Build the Docker image
        run: docker build --target zserver-api -f API.Dockerfile -t zlzforever/zserver-api:202407 .
      - name: Publish the Docker image
        run: docker push zlzforever/zserver-api:202407
